package dev.spring.demo.Data;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;


    /** The Entity annotation is used to specify that the particular class is an Entity Class.
     * Now an Entity is nothing but DataClass (Kotlin) or POJOs (Java).
     * Every Entity represents a row in the table.
     * The Table Annotation maps the DataClass to the Table specified in parameter to the DB.*/
@Entity
@Table(name = "blog")
public class Blog {

    /** Here we have made our variable id as Primary ID using the 'Id' annotation.
     * The GeneratedValue Annotation represents the Generation strategy for values of Primary ID.
     * GenerationType.AUTO specifies that the values are generated automatically.
     * @GeneratedValue(strategy = GenerationType.AUTO) tells Spring that
     * the field is auto-generated and will not be provided by the user, rather, it will be generated by the database.*/
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private int id;

    /** We are using the Column annotation to tell the compiler this variable data needs to be stored
     * in a particular column of the table. We can skip this part if the name of the column in table
     * and variable are same. But it's advised to use it for double check purpose.(Best Practice) **/
    @Column(name = "title")
    private String title;
    @Column(name = "content")
    private String content;

    public Blog(){ }

    public Blog(
            String title,
            String content
    ){
        this.setTitle(title);
        this.setContent(content);
    }

    public Blog(
            int id,
            String title,
            String content
    ) {
        this.setId(id);
        this.setTitle(title);
        this.setContent(content);
    }

    public int getId(){
        return id;
    }
    public void setId(int id){
        this.id = id;
    }

    public String getTitle(){
        return title;
    }
    public void setTitle(String title){
        this.title = title;
    }

    public String getContent(){
        return content;
    }
    public void setContent(String content){
        this.content = content;
    }


    @Override
    public String toString(){
        return "Blog{" +
                "id =" +id +
                ", title ='" +title+ '\'' +
                ", content='" +content+ '\''+
                '}';
    }

}
